src/main/java/com/pd/gilgeorigoreuda/GilgeoriGoreudaApplication.java, src/main/java/com/pd/gilgeorigoreuda/common/entity/BaseTimeEntity.java, src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/Review.java, src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/ReviewComment.java, src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/ReviewImage.java, src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/ReviewLike.java, src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/package-info.java, src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/FoodCategory.java, src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/FoodType.java, src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/PurchaseType.java, src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/Store.java, src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreFavorite.java, src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreLocation.java, src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreRatingSum.java, src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreType.java, src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreVisit.java, src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreVisitCount.java, src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/package-info.java, src/main/java/com/pd/gilgeorigoreuda/store/exception/NoSuchFoodTypeException.java, src/main/java/com/pd/gilgeorigoreuda/store/exception/NoSuchPurchaseTypeException.java, src/main/java/com/pd/gilgeorigoreuda/store/exception/NoSuchStoreTypeException.java, src/main/java/com/pd/gilgeorigoreuda/store/exception/package-info.java, src/main/java/com/pd/gilgeorigoreuda/user/domain/entity/User.java, src/main/java/com/pd/gilgeorigoreuda/user/domain/entity/package-info.java
- close: #6 
초기 Entity 작성
1. User Entity
2. Store Entity
3. ReviewImage Entity
4. Review Entity
5. ReviewLike Entity
6. ReviewComment Entity
7. StoreRateSum Entity
8. StoreLocation Entity
9. StoreVisit Entity
10. StoreVisitCount Entity
11. StoreCategory Entity
12. StoreFavorite Entity
=> feature/#6 초기 Entity 작성

src/main/java/com/pd/gilgeorigoreuda/common/config/package-info.java, src/main/java/com/pd/gilgeorigoreuda/store/controller/StoreController.java, src/main/java/com/pd/gilgeorigoreuda/store/controller/package-info.java, src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/Store.java, src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreLocation.java, src/main/java/com/pd/gilgeorigoreuda/store/dto/request/BusinessDateRequest.java, src/main/java/com/pd/gilgeorigoreuda/store/dto/request/StoreCreateRequest.java, src/main/java/com/pd/gilgeorigoreuda/store/dto/request/StoreLocationRequest.java, src/main/java/com/pd/gilgeorigoreuda/store/dto/request/StoreUpdateRequest.java, src/main/java/com/pd/gilgeorigoreuda/store/dto/request/package-info.java, src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreCreateResponse.java, src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreLocationResponse.java, src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreResponse.java, src/main/java/com/pd/gilgeorigoreuda/store/dto/response/UpdateStoreResponse.java, src/main/java/com/pd/gilgeorigoreuda/store/dto/response/package-info.java, src/main/java/com/pd/gilgeorigoreuda/store/exception/BusinessDateResponseReflectionException.java
- close: #13 
1. controller
2. request
3. response
1. controller 기능 구현에 필요한 request, response 
2. Store, StoreLocation 수정
3. 요청 데이터 검증
=> feature/#13 StoreController 구현

src/main/java/com/pd/gilgeorigoreuda/store/controller/StoreController.java, src/main/java/com/pd/gilgeorigoreuda/store/controller/package-info.java, src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/Store.java
- close: #14 
user 와 store 연관관계 설정
user와 store ManyToOne 관계 설정
=> refactor/#14 User Store Entity 연관관계 매핑

src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java, src/main/java/com/pd/gilgeorigoreuda/review/controller/package-info.java, src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/Review.java, src/main/java/com/pd/gilgeorigoreuda/review/dto/request/ReviewRequest.java, src/main/java/com/pd/gilgeorigoreuda/review/dto/request/package-info.java, src/main/java/com/pd/gilgeorigoreuda/review/dto/response/ReviewResponse.java, src/main/java/com/pd/gilgeorigoreuda/review/dto/response/package-info.java, src/main/java/com/pd/gilgeorigoreuda/review/repository/ImageRepository.java, src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewRepository.java, src/main/java/com/pd/gilgeorigoreuda/review/repository/package-info.java, src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java, src/main/java/com/pd/gilgeorigoreuda/review/service/package-info.java, src/main/resources/application-local.yml, src/test/java/com/pd/gilgeorigoreuda/review/repository/ReviewRepositoryTest.java
- close: #21 
리뷰 CRUD 기능 구현
1. review create
2. review update
3. review delete
=> feature/#21 리뷰 CRUD 기능

src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StorePreference.java, src/main/resources/application-local.yml, src/test/resources/application-test.yml
- close: #35 
Storefavorites -> StorePreferences로 이름 변경
DB Table 이름과 Entity 이름 싱크 수정
=> refactor/#35 Storefavorites -> StorePreferences로 이름 변경

src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java, src/main/java/com/pd/gilgeorigoreuda/review/dto/request/ReviewCommentRequest.java, src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewCommentRepository.java, src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewCommentService.java
- close: #34 
커뮤니티 댓글 등록 기능.
memberId는 추후 토큰 사용시 변경할 예정이라 PathVariable로 넣어둠.
=> feature/#34 리뷰 댓글 등록 기능 구현

src/main/java/com/pd/gilgeorigoreuda/common/page/PageInfo.java, src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java, src/main/java/com/pd/gilgeorigoreuda/review/dto/response/ReviewCommentListResponse.java, src/main/java/com/pd/gilgeorigoreuda/review/dto/response/ReviewCommentResponse.java, src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewCommentRepository.java, src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewCommentService.java
- close: #34 
리뷰 아이디로 리뷰 댓글 조회
=> feature/#34-리뷰 댓글 조회기능 구현

src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java, src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/ReviewComment.java, src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewCommentService.java
ReviewCommentId와 memberId 확인 후 업데이트할 수 있도록 구현.
- close: #34 
수행한 작업을 1~2줄 사이로 요약해주세요.
댓글 수정 기능
주요 기능 및 로직에 관해 설명해주세요.
=> feature/#34-리뷰 댓글 업데이트 구현:

src/main/java/com/pd/gilgeorigoreuda/statistics/controller/HotPlaceController.java, src/main/java/com/pd/gilgeorigoreuda/statistics/domain/HotPlace.java, src/main/java/com/pd/gilgeorigoreuda/statistics/repository/HotPlaceRepository.java, src/main/java/com/pd/gilgeorigoreuda/statistics/schedule/KeywordSchedule.java, src/main/java/com/pd/gilgeorigoreuda/statistics/service/HotPlaceService.java, src/main/java/com/pd/gilgeorigoreuda/statistics/service/KeywordService.java, src/main/resources/application-local.yml
- close: #27 
top 10 database 생성
top 10 insert, getAll 기능 구현
top 10 조회, 저장 기능 구현
top 10 db 추가
=> feature/#27 top 10 database 생성, top 10 insert, getAll 기능 구현

src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java, src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewCommentService.java
ReviewCommentId와 memberId 확인 후 삭제할 수 있도록 구현.
- close: #34 
댓글 삭제 기능
=> feature/#34-리뷰 댓글 삭제 구현:

src/main/java/com/pd/gilgeorigoreuda/community/controller/CommunityController.java, src/main/java/com/pd/gilgeorigoreuda/community/service/CommunityService.java, src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewRepository.java
- close: #18 
리뷰 모아보기 기능 구현
default 최신순, 평점순, 좋아요순가능하도록 페이징으로 구현
=> feature/#18 리뷰 모아보기 기능 구현

src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/Store.java, src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StreetAddress.java
- close: #66 
가게의 도로명주소 타입을 String 에서 StreetAddress 임베디드 타입으로 변경
1. Store의 streetAddress 를 StreetAddress 타입으로 변경
2. StreetAddress 클래스 작성
반경안에 있는 가게조회를 하는 경우 모든 가게의 위경도값으로 거리를 계산하기 보단 우선 주소로 가게를 먼저 필터링을 거쳐
계산할 가게의 크기를 줄여서 DB 성능 향상 기대
=> refactor/#66 가게의 도로명주소 타입을 String 에서 StreetAddress 임베디드 타입으로 변경

src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java
- close: #76 
평점과 likeCount 데이터베이스에 들어가도록 수정
=> refactor/#76 review 리뷰 등록 수정

src/main/java/com/pd/gilgeorigoreuda/common/exception/ExceptionType.java, src/main/java/com/pd/gilgeorigoreuda/store/controller/StoreReportController.java, src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreReportHistory.java, src/main/java/com/pd/gilgeorigoreuda/store/exception/NoRepoterMemberException.java, src/main/java/com/pd/gilgeorigoreuda/store/exception/NoSuchStoreReportHistoryException.java, src/main/java/com/pd/gilgeorigoreuda/store/repository/StoreReportHistoryRepository.java, src/main/java/com/pd/gilgeorigoreuda/store/service/StoreReportService.java, src/main/resources/application-local.yml
- close: #87 
본인이 작성한 신고내역만 삭제
=> feature/#87 본인이 신고한 가게만 신고취소 가능하도록 만듬

src/main/java/com/pd/gilgeorigoreuda/member/controller/MemberController.java, src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java, src/main/java/com/pd/gilgeorigoreuda/store/controller/StorePreferenceController.java
- close: #94
StorePreference, Member, Review Controller endpoint 수정
1. StorePerference Controller
2. Member Controller
3. Review Controller
endpoint 수정
바뀐 endpoint 확인해주세요~
=> refactor/#94 controller endpoint 수정

src/main/java/com/pd/gilgeorigoreuda/common/exception/ExceptionType.java, src/main/java/com/pd/gilgeorigoreuda/common/util/DistanceCalculator.java, src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreVisitRecord.java, src/main/java/com/pd/gilgeorigoreuda/visit/controller/VisitController.java, src/main/java/com/pd/gilgeorigoreuda/visit/dto/request/VisitVerifyRequest.java, src/main/java/com/pd/gilgeorigoreuda/visit/dto/response/VisitResponse.java, src/main/java/com/pd/gilgeorigoreuda/visit/exception/NoSuchStoreVisitRecordException.java, src/main/java/com/pd/gilgeorigoreuda/visit/exception/TimeOutException.java, src/main/java/com/pd/gilgeorigoreuda/visit/exception/TooLongDistanceException.java, src/main/java/com/pd/gilgeorigoreuda/visit/repository/StoreVisitRecordRepository.java, src/main/java/com/pd/gilgeorigoreuda/visit/service/VisitService.java, src/main/resources/application-local.yml, src/test/java/com/pd/gilgeorigoreuda/common/util/DistanceCalculatorTest.java
- close: #99 
사용자가 방문 인증을 원하는 가게 근처에서 방문 인증을 요청한다.
1. 사용자가 가게 위치 반경 10미터 이내에서 인증을 요청한다 -> 10미터 이내가 아니면 예외처리
2. 가게 방문 기록이 있다면 인증 여부를 true로 변경한다.
=> feature/#99 가게 방문 인증 요청 기능 구현

src/main/java/com/pd/gilgeorigoreuda/community/controller/CommunityController.java
- close: #105 
community-sort-desc로 변경
=> refactor/#105-community-sort-desc로 변경

src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java, src/main/java/com/pd/gilgeorigoreuda/review/dto/response/ReviewMemberResponse.java, src/main/java/com/pd/gilgeorigoreuda/review/dto/response/ReviewResponse.java, src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewRepository.java, src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java, src/main/resources/application-local.yml
- close: #114 
가게 아이디로 리뷰 조회하기 기능 구현
=> feature/#114 가게 아이디로 리뷰 조회하기

src/main/java/com/pd/gilgeorigoreuda/common/exception/ExceptionType.java, src/main/java/com/pd/gilgeorigoreuda/store/exception/NullReportException.java, src/main/java/com/pd/gilgeorigoreuda/store/service/StoreReportService.java, src/main/resources/application-local.yml
- close: #125 
content가 없는 신고일 때 필터링 추가
=> feature/#125 content가 없는 신고 필터링 추가

src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/Review.java
- close: #131 
리뷰 이미지 연관 관계로 넣도록 초기화
=> feature/#131 리뷰 이미지 연관 관계로 넣도록 초기화

src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/Review.java, src/main/java/com/pd/gilgeorigoreuda/review/dto/request/ReviewCreateRequest.java
- close: #133 
리뷰 이미지 등록시 이미지에 리뷰 아이디 가지고 들어가도록 수정
=> feature/#133 리뷰 이미지 등록시 이미지에 리뷰 아이디 가지고 들어가도록 수정

src/main/java/com/pd/gilgeorigoreuda/auth/CheckIsMember.java, src/main/java/com/pd/gilgeorigoreuda/auth/MemberInfo.java, src/main/java/com/pd/gilgeorigoreuda/auth/MemberOnly.java, src/main/java/com/pd/gilgeorigoreuda/auth/domain/AuthChecker.java, src/main/java/com/pd/gilgeorigoreuda/auth/domain/Authority.java, src/main/java/com/pd/gilgeorigoreuda/auth/domain/LoginMember.java, src/main/java/com/pd/gilgeorigoreuda/auth/exception/RefreshTokenNotFoundException.java, src/main/java/com/pd/gilgeorigoreuda/auth/exception/UnAuthorizedException.java, src/main/java/com/pd/gilgeorigoreuda/auth/resolver/MemberInfoArgumentResolver.java, src/main/java/com/pd/gilgeorigoreuda/common/config/web/ResolverConfig.java, src/main/java/com/pd/gilgeorigoreuda/common/exception/ExceptionType.java, src/test/java/com/pd/gilgeorigoreuda/HealthControllerTest.java, src/test/java/com/pd/gilgeorigoreuda/settings/ControllerTest.java, src/test/java/com/pd/gilgeorigoreuda/store/controller/StoreControllerTest.java
- close: #137 
접근 권한 검증하는 어노테이션 구현
접근 권한 검증하는 어노테이션 구현
제대로 동작하는지 테스트 진행 후 각 엔드포인트마다 추가하겠습니다!
=> feature/#137 접근 권한 검증

src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/FoodCategory.java, src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/Store.java
- close: #151 
Store의 음식 카테고리 리스트 초기화 및 OneToMany cascade type ALL로 수정
1. OneToMany cascade type ALL로 수정
2. FoodCategory 에 setStore 메소드 추가
=> bug/#151 FoodCategory 연관관계 메소드를 통한 영속문제 수정

src/docs/asciidoc/index.adoc, src/main/java/com/pd/gilgeorigoreuda/search/controller/SearchController.java, src/main/java/com/pd/gilgeorigoreuda/store/controller/StoreController.java, src/main/java/com/pd/gilgeorigoreuda/store/dto/request/StoreCreateRequest.java, src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreResponse.java, src/main/java/com/pd/gilgeorigoreuda/store/service/StoreService.java, src/test/java/com/pd/gilgeorigoreuda/store/controller/StoreControllerTest.java
- close: #153 
가게 조회에 현재 사용자 위치에서 가게 위치 거리 응답 추가
현재 사용자 위치에서 가게까지의 거리 계산 후 응답에 추가
=> feature/#153 가게 조회에 현재 사용자 위치에서 가게 위치 거리 응답 추가

src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java
- close: #150 
store에서 review 조회시 내림차순 정렬 적용
Sort.by("createdAt").descending()를 추가하여 내림차순 정렬 적용
=> refactor/#150 store에서 review 조회시 내림차순 정렬 적용

src/main/java/com/pd/gilgeorigoreuda/search/controller/SearchController.java
- close: #164 
SearchController에 street_address 파라미터 추가
통계 작업을 위한 SearchController에 street_address 파라미터 추가
=> feature/#164 SearchController에 street_address 파라미터 추가

src/main/java/com/pd/gilgeorigoreuda/search/controller/SearchController.java, src/main/java/com/pd/gilgeorigoreuda/search/repository/SearchRepository.java, src/main/java/com/pd/gilgeorigoreuda/search/service/SearchService.java, src/test/java/com/pd/gilgeorigoreuda/search/repository/SearchRepositoryTest.java
- close: #163 
검색한 주소를 통계 작업을 위해 저장하기 위한 로직 추가
검색한 주소를 통계 작업을 위해 저장하기 위한 로직 추가
=> feature/#163 검색한 주소를 통계 작업을 위해 저장하기 위한 로직 추가

src/main/resources/application-local.yml
- close: #166 
카카오 redirect-url yml 수정
=> refactor/#166 카카오 redirect-url yml 수정

src/main/java/com/pd/gilgeorigoreuda/statistics/repository/KeywordRepository.java
- close: #170 
KeywordRepository 수정
KeywordRepository 수정
=> refactor/#170 KeywordRepository 수정

src/main/java/com/pd/gilgeorigoreuda/common/config/web/ResolverConfig.java, src/main/java/com/pd/gilgeorigoreuda/search/controller/SearchController.java, src/main/java/com/pd/gilgeorigoreuda/search/resolver/SearchParameter.java, src/main/java/com/pd/gilgeorigoreuda/search/resolver/SearchParams.java, src/main/java/com/pd/gilgeorigoreuda/search/resolver/SearchParamsArgumentResolver.java, src/main/java/com/pd/gilgeorigoreuda/search/service/SearchService.java
- close: #172 
검색 조건 파라미터들 마다 null 처리 및 하나의 어노테이션으로 통합하여 간소화
검색 조건 파라미터들 마다 null 처리 및 하나의 어노테이션으로 통합하여 간소화
=> feature/#172 검색 조건 파라미터들 마다 null 처리 및 하나의 어노테이션으로 통합하여 간소화

src/main/java/com/pd/gilgeorigoreuda/batch/review/scheduler/ReviewLikeHateBatchScheduler.java, src/main/java/com/pd/gilgeorigoreuda/community/controller/CommunityController.java, src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
- close: #174 
좋아요순으로 정렬되도록 수정.
=> refactor/#174 좋아요순으로 정렬되도록 수정

.github/workflows/dev-cd.yml
- close: #177
dev-cd.yml 문법 오류 해결
dev-cd.yml 문법 오류 해결
=> bug/#177 dev-cd.yml 문법 오류 해결

.github/workflows/dev-cd.yml, src/main/resources/application-prod.yml
- close: #179 
dev cd.yml 수정
dev cd.yml 수정
=> bug/#179 dev cd.yml

.github/workflows/ci.yml, .github/workflows/dev-cd.yml
- close: #181 
dev-cd.yml working directory 수정
dev-cd.yml working directory 수정
=> bug/#181 dev-cd.yml working directory fix

.github/workflows/dev-cd.yml
- close: #183 
dev-cd.yml Dockerfile 경로 수정
dev-cd.yml Dockerfile 경로 수정
=> bug/#183 dev-cd.yml Dockerfile 경로 수정

Dockerfile
- close: #185 
Dockerfile jar file 경로 수정
잘못된 jar file 경로 떄문에 Dockerfile jar file 경로 수정
=> bug/#185 Dockerfile jar file 경로 수정

.github/workflows/dev-cd.yml
- close: #187 
docker build 에서 deploy 단계로 넘어가지 않는 문제 해결을 위한 디버깅
docker build 에서 deploy 단계로 넘어가지 않는 문제 해결을 위한 디버깅
=> bug/#187 docker build 에서 deploy 단계로 넘어가지 않는 문제 해결

.github/workflows/dev-cd.yml
- close: #190 
runs-on을 ubuntu-latest로 변경
runner를 self-hosted에서 github host로 변경
=> bug/#190 runs-on을 ubuntu-latest로 변경

src/main/resources/application-dev.yml
- close: #194 
bean definition overide true 욥션 추가
bean definition overide true 욥션 추가
=> refactor/#194 bean definition overide true 욥션 추가

build.gradle, src/main/java/com/pd/gilgeorigoreuda/common/config/database/DataSourceConfiguration.java, src/main/java/com/pd/gilgeorigoreuda/common/config/database/DataSourceType.java, src/main/java/com/pd/gilgeorigoreuda/common/config/database/RoutingDataSource.java, src/main/resources/application-local.yml
- close: #188 
flyway 적용
flyway 적용
=> feature/#188 flyway 적용

src/main/java/com/pd/gilgeorigoreuda/member/controller/MemberController.java, src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java, src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewPreferenceController.java, src/main/java/com/pd/gilgeorigoreuda/store/controller/StoreController.java, src/main/java/com/pd/gilgeorigoreuda/store/controller/StorePreferenceController.java, src/main/java/com/pd/gilgeorigoreuda/store/controller/StoreReportController.java, src/main/java/com/pd/gilgeorigoreuda/visit/controller/VisitController.java
=> refactor/#198 멤버 토큰 검증으로 수정

src/main/java/com/pd/gilgeorigoreuda/common/config/database/DataSourceConfiguration.java, src/main/java/com/pd/gilgeorigoreuda/common/config/database/RoutingDataSource.java, src/main/java/com/pd/gilgeorigoreuda/login/domain/MemberToken.java, src/main/resources/application-dev.yml, src/main/resources/application-local.yml, src/test/java/com/pd/gilgeorigoreuda/store/controller/StoreControllerTest.java
- close: #202 
dev db url 변경
dev 환경용 db 설정
=> feature/#202 dev db url 변경

build.gradle, src/main/resources/application-prod.yml
- close: #208 
spring actuator
spring actuator
=> feature/#208 spring actuator 디펜던시 추가

.github/workflows/prod-cd.yml
- close: #215 
prod-cd.yml 문법 오류 해결
prod-cd.yml 문법 오류 해결
=> bug/#215 prod-cd.yml 문법 오류 해결

.github/workflows/prod-cd.yml, bluegreen.sh
=> [release] 2차 prod 배포 테스트

.github/workflows/prod-cd.yml
=> [release] 3차 prod 배포 테스트

.github/workflows/prod-cd.yml
- close: #221 
prod-cd.yml 문법 수정
prod-cd.yml 문법 수정
=> bug/#221 prod-cd.yml 문법 수정

.github/workflows/prod-cd.yml
=> [release] 5차 prod 배포

bluegreen.sh
=> [release] 6차 prod 배포 테스트

bluegreen.sh
=> [release] 7차 prod 배포 테스트

bluegreen.sh
- close: #231 
bluegreen.sh 문법 오류 해결
bluegreen.sh 문법 오류 해결
=> bug/#231 bluegreen.sh 문법 오류 해결

bluegreen.sh
=> [release] 8차 prod 배포 테스트

.github/workflows/prod-cd.yml, bluegreen.sh
- close: #234 
bluegreen.sh 문법 수정
bluegreen.sh 문법 수정
=> bug/#234 bluegreen.sh 문법 수정

.github/workflows/prod-cd.yml, bluegreen.sh
=> [release] 9차 prod 배포 테스트

bluegreen.sh, src/main/resources/application-prod.yml
- close: #237 
bluegreen.sh 수정 application-prod.yml 수정
bluegreen.sh 수정 application-prod.yml 수정
=> bug/#237 bluegreen.sh

.github/workflows/prod-cd.yml, bluegreen.sh, src/main/resources/application-prod.yml
=> [release] 10차 prod 배포 테스트

src/main/java/com/pd/gilgeorigoreuda/common/config/web/CorsConfig.java
- close: #240 
cors config 설정 추가
1. nginx 호스트, 포트
2. actuator 호스트, 포트
=> feature/#240 cors config 설정 추가

.github/workflows/prod-cd.yml, src/main/java/com/pd/gilgeorigoreuda/common/config/web/CorsConfig.java
=> [release] 11차 prod 배포 테스트

.github/workflows/prod-cd.yml, bluegreen.sh
=> [release] 12차 prod 배포 테스트

.github/workflows/prod-cd.yml
- close: #248 
prod-cd.yml refactor
prod-cd.yml refactor
=> refactor/#248 prod-cd.yml refactor

.github/workflows/prod-cd.yml, bluegreen.sh
=> [release] 13차 prod 배포 테스트

.github/workflows/prod-cd.yml, src/main/resources/application-blue.yml, src/main/resources/application-green.yml
- close: #251 
applicaton-blue,green.yml
applicaton-blue,green.yml
=> feature/#251 applicaton-blue,green.yml

.github/workflows/prod-cd.yml, src/main/resources/application-blue.yml, src/main/resources/application-green.yml
=> [release] 14차 prod 배포 테스트

.github/workflows/prod-cd.yml, src/main/resources/application-blue.yml, src/main/resources/application-green.yml, src/main/resources/application.yml
=> [release] 16차 prod 배포 테스트

src/main/resources/application-blue.yml, src/main/resources/application-green.yml, src/main/resources/application.yml
=> [release] 18차 prod 배포 테스트

src/main/resources/db/migration/V2__foodcategory.sql
- close: #264 
add food_category table
V2__catecategory.sql 작성
=> feature/#264 add food_category table

src/main/resources/db/migration/V1__init.sql
=> refactor/#267 init.sql

src/main/resources/db/migration/V1__init.sql, src/main/resources/db/migration/V2__foodcategory.sql
=> [release] 20차 prod 배포 테스트

src/main/resources/application-dev.yml, src/main/resources/db/migration/V1__init.sql, src/main/resources/db/migration/V2__foodcategory.sql
=> [release] 21차 prod 배포 테스트

src/main/java/com/pd/gilgeorigoreuda/common/config/database/DataSourceConfiguration.java
=> bug/#270 flyway 수정

.github/workflows/prod-cd.yml, bluegreen.sh, src/main/resources/application-blue.yml, src/main/resources/application-green.yml
- close: #281 
prod-cd.yml 수정 및 actuator 포트 변경
prod-cd.yml 수정 및 actuator 포트 변경
=> refactor/#281 prod-cd.yml 수정 및 actuator 포트 변경

src/main/java/com/pd/gilgeorigoreuda/common/exception/ExceptionType.java, src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/Review.java, src/main/java/com/pd/gilgeorigoreuda/review/exception/NoAuthorityReviewException.java, src/main/java/com/pd/gilgeorigoreuda/review/exception/NoSuchReviewException.java, src/main/java/com/pd/gilgeorigoreuda/review/exception/package-info.java, src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java, src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreVisitRecord.java, src/main/java/com/pd/gilgeorigoreuda/visit/exception/NotVerifiedVisitRecordException.java
- close: #205
방문 인증한 유저만 리뷰 해당 가게 리뷰 작성 가능
방문 인증이 완료된 사용자만 리뷰를 작성할 수 있도록하여 리뷰 신뢰도 향상
=> feature/#205 방문 인증한 유저만 리뷰 해당 가게 리뷰 작성 가능

src/main/java/com/pd/gilgeorigoreuda/login/service/LoginService.java, src/main/java/com/pd/gilgeorigoreuda/member/repository/MemberActiveInfoRepository.java
- close: #287 
- 
사용자 생성시 사용자 활동 정보도 같이 생성
사용자 생성시 사용자 활동 정보도 같이 생성
=> refactor/#287 사용자 생성시 사용자 활동 정보도 같이 생성

src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberInfoResponse.java, src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberPreferenceStoreResponse.java, src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberReviewResponse.java
- close: #294
LocalDateTime 형식 yyyy-MM-dd로  통일
LocalDateTime 형식 yyyy-MM-dd로  통일
=> feature/#294 LocalDateTime 형식 yyyy-MM-dd로  통일

src/main/resources/application-blue.yml, src/main/resources/application-green.yml
- close: #306 
프로덕션 환경 show sql false로 변경
프로덕션 환경 show sql false로 변경
=> refactor/#306 프로덕션 환경 show sql false로 변경

src/main/java/com/pd/gilgeorigoreuda/common/util/DistanceCalculator.java
- close: #309 
가게까지 대략적인 도보 시간 계산 수정
1시간 단위여야 하는데 60초로된 계산식 3600초로 수정
=> refactor/#309 가게까지 대략적인 도보 시간 계산 수정

.github/workflows/dev-cd.yml, .github/workflows/prod-cd.yml, bluegreen.sh, compose-dev.yml, compose-devdb.yml, conf-dev/nginx.conf, deploy-dev.sh
- close: #323 
dev 환경 ci/cd 세팅 변경
1. 깃 서브 모듈에 있는 환경 설정 파일 읽기 작업 추가
2. nginx 컨테이너와 backend-dev 컨테이너를 구축하는  compose-dev.yml 작성
3. deploy-dev.sh 작성
=> refactor/#323 dev ci/cd 세팅 변경

src/main/resources/db/migration/V1__init.sql
- close: #327 
flyway V1__init.sql 에 데이터베이스 생성문 추가
flyway V1__init.sql 에 데이터베이스 생성문 추가
=> refactor/#327 flyway V1__init.sql 에 데이터베이스 생성문 추가

src/test/java/com/pd/gilgeorigoreuda/settings/IntegrationTest.java, src/test/java/com/pd/gilgeorigoreuda/settings/ServiceTest.java, src/test/java/com/pd/gilgeorigoreuda/store/service/StoreServiceTest.java
- close: #337 
Service 계층 단위 테스트를 위한 전체적으로 필요한 코드 모듈화
ServiceTest 클래스 작성
=> feature/#337 서비스 계층 단위 테스트를 위한 템플릿 구현

src/main/java/com/pd/gilgeorigoreuda/store/dto/request/StoreCreateRequest.java, src/test/java/com/pd/gilgeorigoreuda/settings/IntegrationTest.java, src/test/java/com/pd/gilgeorigoreuda/settings/ServiceTest.java, src/test/java/com/pd/gilgeorigoreuda/settings/builder/DataBuilder.java, src/test/java/com/pd/gilgeorigoreuda/store/service/StoreServiceTest.java
- close: #338 
저장하려는 가게 위경도 반경 10미터 안에 존재하는 가게가 없으면 성공 아니면 예외 발생
새로 제보하려는 위치의 위경도 반경 10미터 이내에 이미 존재하는 가게가 있으면 AlreadyExistInBoundaryException 발생,
존재하지 않으면 제보 성공
=> feature/#338 저장하려는 가게 위경도 반경 10미터 안에 존재하는 가게가 없으면 성공 아니면 예외 발생

src/main/java/com/pd/gilgeorigoreuda/common/exception/ExceptionType.java, src/main/java/com/pd/gilgeorigoreuda/store/service/StoreService.java, src/test/java/com/pd/gilgeorigoreuda/store/service/StoreServiceTest.java
- close: #342 
가게 정보 업데이트 성공, 실패 케이스 단위 테스트
1. 가게 정보 업데이트 성공 케이스
2. 유효하지 않은 가게 id로 가게 업데이트 시
3. 유효하지 않은 회원 id로 가게 업데이트 시
=> feature/#342 가게 정보 업데이트 단위 테스트

src/main/java/com/pd/gilgeorigoreuda/common/util/DistanceCalculator.java
- close: #345 
변수명 가독성있게 변경
단순히 a,b같은 수학공식명에서 가독성있고 무슨 변수인지 쉽게 알수있게 변수명 변경
=> refactor/#345 변수명 가독성있게 변경

src/test/java/com/pd/gilgeorigoreuda/settings/ServiceTest.java, src/test/java/com/pd/gilgeorigoreuda/store/service/StoreServiceTest.java
- close: #344 
가게 조회 단위테스트
가게 조회 성공, 실패 케이스 단위 테스트
=> feature/#344 단일 가게 조회 성공/실패 단위 테스트

src/test/java/com/pd/gilgeorigoreuda/image/service/ImageServiceTest.java
- close: #351 
이미지 업로드 시 예외 케이스 정상 작동 테스트
이미지가 null이거나 허용 갯수 초과일때 예외 발생 확인 테스트
=> feature/#351 ImageService 예외케이스 단위 테스트

src/main/java/com/pd/gilgeorigoreuda/store/repository/StoreNativeQueryRepository.java, src/main/java/com/pd/gilgeorigoreuda/store/service/StoreService.java, src/test/java/com/pd/gilgeorigoreuda/store/service/StoreServiceTest.java
- close: #349
가게 정보 변경 서비스 로직 수정
변경하려는 가게의 아이디는 이미 반경안에 존재하는 가게 확인에서 제외
=> refactor/#349 가게 정보 변경 서비스 로직 수정
